name: Api CI


on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    services: 
      mongodb:
        image: mongo:4.0
        ports: 
          - 27017:27017
          
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.x

      - name: Install dependencies
        run: |
          yarn install
          
      - name: Tsc
        run: |
          yarn tsc
